// Auto-generated by scripts/generate-terminal-content.mjs
// Do not edit manually - run "pnpm generate" to regenerate

export const version = "0.1.0";

// Command outputs
export const CMD_ABOUT = `pi-agent-just v0.1.0
Browser-based AI coding agent sandbox.
Terminal on the right, Code Studio on the left.

Built on just-bash for secure sandboxed execution
and pi-coding-agent for the AI agent runtime.

Commands:
  about       About this project
  github      GitHub repository

Or chat with the AI agent naturally.
`;

export const CMD_INSTALL = `pnpm install

Usage:
  # Set API key
  export ANTHROPIC_API_KEY=sk-ant-...
  # or
  export OPENROUTER_API_KEY=sk-or-...

  # Start dev server
  pnpm dev
`;

export const CMD_GITHUB = "https://github.com/niclas-niclas/pi-agent-just\n";

// File contents (generated from repo)
export const FILE_README = `# pi-agent-just

Browser-based AI coding agent sandbox. Terminal on the left, code studio on the right.

Built on [just-bash](https://github.com/vercel-labs/just-bash) for secure sandboxed execution and [pi-coding-agent](https://github.com/niclas-niclas/pi-coding-agent) for the AI agent runtime.

## Architecture

\`\`\`
┌────────────────────┬──────────────────────────────────────┐
│                    │  [◨]  4 files          [Apply][Reset] │
│                    ├──[index.ts]──[App.tsx]──[preview]─────┤
│  Terminal          │┌────────┬────────────────────────────┐│
│  (AI chat + bash)  ││ src/   │  1│ import { useState }    ││
│                    ││  index │  2│ from "react";          ││
│                    ││  App   │  3│                        ││
│                    ││        │  4│ export default ...     ││
│                    │└────────┴────────────────────────────┘│
└────────────────────┴──────────────────────────────────────┘
\`\`\`

**Left panel** — Terminal with AI agent. Chat naturally or run bash commands directly. Commands execute in a sandboxed virtual filesystem.

**Right panel** — Code Studio. Tabbed file viewer with Shiki syntax highlighting, live HTML preview, markdown rendering, JSON formatting. File tree sidebar with change indicators.

**Sandbox** — All file operations happen in an in-memory OverlayFS. Nothing touches disk until you click **Apply**. Click **Reset** to discard everything.

## Quick Start

\`\`\`bash
# Install dependencies
pnpm install

# Set API key (pick one)
export ANTHROPIC_API_KEY=sk-ant-...
# or
export OPENROUTER_API_KEY=sk-or-...

# Optional: point to a real project directory
export SANDBOX_ROOT=/path/to/your/project

# Start dev server
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## How It Works

### Agent API (\`/api/agent\`)

POST endpoint that streams SSE events from the AI agent. The agent has access to sandboxed tools:

| Tool | Description |
|------|-------------|
| \`bash\` | Run commands in the virtual bash environment |
| \`read\` | Read files from the overlay filesystem |
| \`write\` | Create/overwrite files (in-memory) |
| \`edit\` | Edit existing files with string replacement |
| \`ls\` | List directory contents |

### Sandbox API (\`/api/sandbox\`)

| Method | Description |
|--------|-------------|
| \`GET /api/sandbox\` | List all overlay changes (created/modified/deleted files) |
| \`POST /api/sandbox\` \`{action:"apply"}\` | Write all changes to disk |
| \`POST /api/sandbox\` \`{action:"reset"}\` | Discard all in-memory changes |

### Code Studio

- **Syntax highlighting** — Shiki with github-dark/github-light themes, 15+ languages
- **Live preview** — HTML (sandboxed iframe), Markdown, SVG, JSON
- **File tree** — Auto-collapsing single-child directories, change type indicators (+/~/-)
- **Tabs** — Middle-click close, Cmd+W close, Cmd+[ / Cmd+] cycle, Cmd+B toggle sidebar
- **Draggable splitter** — Resize terminal and studio panels

## Environment Variables

| Variable | Default | Description |
|----------|---------|-------------|
| \`ANTHROPIC_API_KEY\` | — | Anthropic API key |
| \`OPENROUTER_API_KEY\` | — | OpenRouter API key (takes priority) |
| \`PI_MODEL\` | \`claude-haiku-4.5\` | Model ID |
| \`SANDBOX_ROOT\` | bundled \`_agent-data/\` | Directory to mount as the sandbox root |

## Custom just-bash Extensions

This project depends on a forked/extended version of \`just-bash\` (>= 2.11.6, not yet published to npm). We added change-tracking and apply/reset APIs to \`OverlayFs\` that the upstream \`2.11.5\` release does not have:

| Method | Purpose |
|--------|---------|
| \`getOverlayChanges()\` | List all in-memory file changes (created/modified/deleted) — powers the file tree and code viewer |
| \`resetOverlay()\` | Discard all in-memory writes, revert to real disk state — **Reset** button |
| \`applyChange(path)\` | Write a single file's in-memory content to real disk |
| \`applyAllChanges()\` | Write all changes to disk — **Apply** button |
| \`snapshotBootstrap()\` | Exclude Bash init files (\`/bin/\`, \`/dev/\`, etc.) from the change list |
| \`OverlayChange\` type | \`{ path: string, type: "created" \\| "modified" \\| "deleted", content?: string }\` |

Without these methods, the Sandbox API (\`/api/sandbox\`) cannot function and the Code Studio panel would have no data.

**To install locally** (until the upstream publishes these changes):

\`\`\`bash
# In the just-bash repo
pnpm pack --pack-destination /tmp/

# In this repo
pnpm add file:/tmp/just-bash-2.11.6.tgz
\`\`\`

## Tech Stack

- **Next.js 16** (App Router, Turbopack)
- **just-bash** — TypeScript bash interpreter + OverlayFS
- **pi-coding-agent** — AI agent session with tool use
- **Shiki 4** — Syntax highlighting (browser bundle, no WASM)
- **Tailwind CSS 4** — Styling with CSS custom properties for theming
- **React 19** — UI

## License

Apache-2.0
`;

export const FILE_PACKAGE_JSON = `{
  "name": "website",
  "version": "0.1.0",
  "private": true
}`;
